// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rl_bl.Context;

namespace kubaapi.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20190508181206_shortnameChapterAdded")]
    partial class shortnameChapterAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("rl_contract.Models.Anamnese", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CountOfPositivAnswers");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name");

                    b.Property<int?>("PatientId");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasFilter("[PatientId] IS NOT NULL");

                    b.ToTable("Anamnesen");

                    b.HasData(
                        new { Id = 1, CountOfPositivAnswers = -1, Date = new DateTime(2019, 5, 8, 20, 12, 5, 889, DateTimeKind.Local), Name = "Anamnese (Fragebogen / Kinder)", PatientId = 1 }
                    );
                });

            modelBuilder.Entity("rl_contract.Models.AnamneseChapter", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnamneseId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("AnamneseId");

                    b.ToTable("AnamneseChapters");

                    b.HasData(
                        new { Id = 1, AnamneseId = 1, Name = "0. Allgemeines" },
                        new { Id = 2, AnamneseId = 1, Name = "I. Schwangerschaft" },
                        new { Id = 3, AnamneseId = 1, Name = "II. Geburt" },
                        new { Id = 4, AnamneseId = 1, Name = "- ENDE 1 Teil(7 - 8 JA Antworten) + Frage 18./ 22.a) / 24. -> Bitte beantworten Sie die folgenden Fragen, bis sie altersgemäß nicht mehr zutreffen - " },
                        new { Id = 5, AnamneseId = 1, Name = "III. Schulzeit: 6. – 8. Lebensjahr" },
                        new { Id = 6, AnamneseId = 1, Name = "IV. 8. - 10. Lebensjahr" },
                        new { Id = 7, AnamneseId = 1, Name = "V. Zusätzliche Angaben" }
                    );
                });

            modelBuilder.Entity("rl_contract.Models.AnamneseQuestion", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnamneseChapterId");

                    b.Property<string>("Label");

                    b.Property<string>("MetaInfo");

                    b.Property<string>("TextPrefix");

                    b.Property<string>("TextValue");

                    b.Property<string>("Type");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("AnamneseChapterId");

                    b.ToTable("AnamneseQuestions");

                    b.HasData(
                        new { Id = 1, AnamneseChapterId = 1, Label = "Leidensdruck beim Kind?", Type = "textarea", Value = "" },
                        new { Id = 2, AnamneseChapterId = 1, Label = "Was wurde/ wird unternommen um den Leidensdruck zu verbessern?", Type = "textarea", Value = "" },
                        new { Id = 3, AnamneseChapterId = 1, Label = "Wie viele Kinder haben Sie entbunden?", Type = "input", Value = "" },
                        new { Id = 4, AnamneseChapterId = 1, Label = "Welches Kind bei mehreren?", Type = "input", Value = "" },
                        new { Id = 5, AnamneseChapterId = 1, Label = "Hatten Sie vorher Fehlgeburten? Warum?", Type = "input", Value = "" },
                        new { Id = 6, AnamneseChapterId = 1, Label = "Wurden Sie mit ihrem Kind aufgrund von IVF (künstliche Befruchtung) schwanger?", Type = "radioYesNo", Value = "" },
                        new { Id = 7, AnamneseChapterId = 2, Label = "Als Sie schwanger waren, hatten Sie irgendwelche medizinischen Probleme?", MetaInfo = "hoher Blutdruck, Hyperemesis gravidarum, drohende Fehlgeburt, vorzeitige Wehen, verordnete Bettruhe, Zwischenblutungen, Eisenmangel, Erkrankungen / Infektionen, Alkohol, Drogen, Umweltgifte, Medikamente, Ernährung, Flugreise, Sauna", TextPrefix = "Falls ja, bitte Einzelheiten angeben: ", Type = "radioYesNo", Value = "" },
                        new { Id = 8, AnamneseChapterId = 2, Label = "Hatten Sie eine starke Virusinfektion in den ersten 13. Wochen Ihrer Schwangerschaft?", Type = "radioYesNo, textarea", Value = "" },
                        new { Id = 9, AnamneseChapterId = 2, Label = "Standen Sie während Ihrer Schwangerschaft (besonders im 6. Monat) unter starkem emotionalen Stress?", Type = "radioYesNo", Value = "" },
                        new { Id = 10, AnamneseChapterId = 2, Label = "Sind während der Schwangerschaft diagnostische Verfahren durchgeführt worden?", MetaInfo = "Ultraschall, Sonografie, Röntgen, Fruchtwasseruntersuchung o.ä.", TextPrefix = "Falls ja, bitte Einzelheiten angeben: ", Type = "radioYesNo, textarea", Value = "" },
                        new { Id = 11, AnamneseChapterId = 2, Label = "Erfolgte vor oder während der Schwangerschaft eine Hormonbehandlung", MetaInfo = "z.B. Progesteron Gabe in der 6. Woche", TextPrefix = "Falls ja, welche und wann:", Type = "radioYesNo, textarea", Value = "" },
                        new { Id = 12, AnamneseChapterId = 2, Label = "Wurde Ihr Kind früher (vor der 37. SSW) oder später (nach der 42. SSW) als zum errechneten Termin(+/ -2 Tage) geboren?", TextPrefix = "Falls ja, bitte Einzelheiten angeben: ", Type = "radioYesNo, textarea", Value = "" },
                        new { Id = 13, AnamneseChapterId = 3, Label = "War der Geburtsprozess ungewöhnlich oder besonders schwierig?", MetaInfo = "Wehen, Geburtsdauer, Medikamente, Kaiserschnitt, Zange, Saugglocke, Sturzgeburt, Steißlage, Fruchtwasser, Kristellern, gerissen/ geschnitten", TextPrefix = "Falls ja, bitte Einzelheiten angeben: ", Type = "radioYesNo, textarea", Value = "" },
                        new { Id = 14, AnamneseChapterId = 3, Label = "War Ihr Kind klein bezogen auf den Geburtszeitpunkt?", MetaInfo = "< 2500g oder > 4000 - 4300g", TextPrefix = "Geben Sie bitte das Geburtsgewicht die Geburtslänge und den Kopfumfang an.", Type = "radioYesNo, textarea", Value = "" },
                        new { Id = 15, AnamneseChapterId = 3, Label = "Gab es irgendwelche Besonderheiten an Ihrem Baby nach der Geburt? Brauchte es Intensivpflege? Kam es dadurch zu einer längeren Trennung? Wochenbettdepression?", MetaInfo = "Schädelverformung, viele blaue Flecken, Nabelschnur um den Hals, deutlich blaue Verfärbung, schwere Neugeborenengelbsucht, Lanugo-Behaarung, stark mit Käseschmiere bedeckt, Gelbsucht, Fußdeformitäten, Hüftdysplasie", TextPrefix = ":Falls ja, bitte Einzelheiten angeben: ", Type = "radioYesNo", Value = "" },
                        new { Id = 16, AnamneseChapterId = 3, Label = "Wie waren die APGAR – Werte Ihres Kindes? (siehe Mutterpass ……/……/……) und der pH-Wert:", MetaInfo = "", TextPrefix = "Zusätzliche Angaben zur Schwangerschaft und Geburt (z.B. Einnahme der Pille ?) ", Type = "textarea", Value = "" },
                        new { Id = 17, AnamneseChapterId = 3, Label = "Hatte Ihr Kind in den ersten 13 Lebenswochen Schwierigkeiten beim Saugen an der Brust, beim Trinken aus der Flasche ? Hat es viel gespuckt ? ", MetaInfo = "Wie lange gestillt, Dauer einer Mahlzeit, Zeitabstände zwischen den Mahlzeiten, Saugbewegungen", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 18, AnamneseChapterId = 3, Label = "Dauerte es auffallend lange, bis es seinen Kopf hochhalten konnte? Oder hat es den Kopf  sehr früh überstreckt gehalten?", MetaInfo = "> 4 Monat", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 19, AnamneseChapterId = 3, Label = "War Ihr Kind in den ersten 6 Lebensmonaten ein auffallend ruhiges Baby, so ruhig, dass Sie manchmal befürchteten,es sei in seinem Bettchen gestorben?", MetaInfo = "", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 20, AnamneseChapterId = 3, Label = "War Ihr Kind zwischen dem 6. und 18. Lebensmonat sehr aktiv und fordernd? Schlief es wenig und schrie es ständig?", MetaInfo = "verstopfte Nase, Mundatmer, schnarchendes Baby, Schlafprobleme, mochte nicht liegen → Druck im Mittelohr (unreife Schluckmuster), ADHS", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 21, AnamneseChapterId = 3, Label = "Als Ihr Kind alt genug war, in der Karre zu sitzen oder sich im Kinderbett zum Stand hochzuziehen, bewegte es sich dort heftig schaukelnd hin und her, so dass sich Karre oder Bett mitbewegten?", MetaInfo = "Wie ließ es sich beruhigen? → heftiges Schaukeln, Autofahren; Stereotype Bewegungen wie im Liegen den Kopf hin und her bewegen; Schreien beim Hinlegen?", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 22, AnamneseChapterId = 3, Label = "War Ihr Kind ein kleiner „Kopfstoßer“, d.h. stieß es absichtlich mit dem Kopf gegen feste Gegenstände ? Gibt es eine Vorgeschichte von Kopfverletzungen ? Wo waren die Kopfverletzungen?", MetaInfo = "(präfrontaler Cortex – kein INPP Kind)", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 23, AnamneseChapterId = 3, Label = "Hat Ihr Kind sich nicht zum richtigen Zeitpunkt (ca. ab 6. Monat) oder nur mit physiotherapeutischer Unterstützung vom Rücken auf den Bauch gedreht?", MetaInfo = "vom Bauch auf den Rücken ab 8. Monat postnatal", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 24, AnamneseChapterId = 3, Label = "Hat ihr Kind nicht ausreichend/ wenig Zeit in BL verbracht bis zum Krabbeln?", MetaInfo = "mochte es die BL, Tagesablauf des Babys, Maxi-Kosi, Wippe, Spreizwindel", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 25, AnamneseChapterId = 3, Label = "Hat Ihr Kind, anstatt zunächst auf dem Bauch zu kriechen und dann auf den Händen und Knien zu krabbeln, sich auf andere Weise fortbewegt(z.B.rollend, auf dem Po rutschend, im „Bärengang“ auf Händen und Füßen)?", MetaInfo = "(Kriechen = ab 7. - 8. Monat, homolateral die ersten 2 – 4 Wochen; Robben = ab 8. Monat, kontralateral; Krabbeln = ab 8. - 9.Monat, ab 11.Monat flüssig; Sitzen = ab 8.Monat; Stand = ab 8.Monat mit festhalten, ab 10.bis 11.Monat frei)", TextPrefix = "Falls ja, bitte Einzelheiten angeben: ", Type = "radioYesNo, textarea", Value = "" },
                        new { Id = 26, AnamneseChapterId = 3, Label = "Hat Ihr Kind auffallend spät (> 1,5 Jahre) oder früh (< 12 Monate) laufen gelernt?", MetaInfo = "Lauflerngeräte, Babywippe, Maxi- Kosi, Hopser", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 27, AnamneseChapterId = 3, Label = "Hat Ihr Kind spät sprechen gelernt (Zwei- und Dreiwortsätze) (> 2,5 Jahre)?", MetaInfo = "eigene Sprache, gesabbert, Schwierigkeiten bei bestimmten Lauten, Gesungene Sprache", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 28, AnamneseChapterId = 3, Label = "Hatte es während der ersten 18 Lebensmonate irgendwelche Krankheiten, die mit hohem Fieber und / oder Krämpfen verbunden waren ? ", MetaInfo = "sehr schnell, sehr hoch gefiebert, Narkose", TextPrefix = "Falls ja, bitte Einzelheiten angeben (konnte es nach der Krankheit etwas nicht mehr so gut wie vorher?)", Type = "radioYesNo, textarea", Value = "" },
                        new { Id = 29, AnamneseChapterId = 3, Label = "Hatte es  auffällige Schwierigkeiten sich selber anziehen zu lernen?", MetaInfo = "Reihenfolge, falsch herum, Schleife (>5 bis 5,6Jahre), Knöpfe, Reißverschluss, „bequem / faul“, Hose fällt schwer anzuziehen", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 30, AnamneseChapterId = 3, Label = "Litt bzw. leidet Ihr Kind unter Hautproblemen (trockene Haut, Milchschorf,  Neurodermitis, Ekzeme) oder Asthma(Husten, Reizhusten)?", MetaInfo = "", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 31, AnamneseChapterId = 3, Label = "Zeigt es irgendwelche allergische Reaktionen? ", MetaInfo = "Allergien in der Familie, Heuschnupfen, Auslöser: Milch/Eier/Weizen, ständig laufende Nase, Suchtmittel", TextPrefix = "Falls ja, bitte Einzelheiten angeben: ", Type = "radioYesNo, textarea", Value = "" },
                        new { Id = 32, AnamneseChapterId = 3, Label = "Gab es irgendwelche auffälligen Reaktionen nach den  Impfungen?", MetaInfo = "längeres schlafen, erhöhte Temperatur", TextPrefix = "Falls ja, bitte Einzelheiten angeben: ", Type = "radioYesNo, textarea", Value = "" },
                        new { Id = 33, AnamneseChapterId = 3, Label = "Lutschte Ihr Kind bis etwa zum 5. Lebensjahr oder länger am Daumen? (Hatte es einen Schnuller (> 2 LJ?), Kuscheltier)", MetaInfo = "", TextPrefix = "Falls ja, an welchem (links, rechts):", Type = "radioYesNo, input", Value = "" },
                        new { Id = 34, AnamneseChapterId = 3, Label = "Machte oder macht  Ihr Kind auch noch nach dem Alter von 5 Jahren gelegentlich ins Bett?", MetaInfo = "Wann war es trocken? Toilettentraining, spinaler Galant, gehäufte Mittelohrentzündungen, Hypoglykämie, nächtlicher O² Mangel, viel Milch Trinker", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 35, AnamneseChapterId = 3, Label = "Zusätzliche Angaben zum Vorschulalter (Auffälligkeiten in der Motorik, Sport, externe Betreuung, Trennungsangst, Schreckhaft, Ängstlich, viele Freunde, Einzelgänger, Streit, Reaktionen auf Veränderungen, emotionale Auffälligkeiten, was sagen die Erzieher über das Kind, schneiden, malen, puzzeln, Körperhaltung, Spielverhalten, zündeln, Beziehung zu Tieren, Verletzungen)", MetaInfo = "", TextPrefix = "", Type = "radioYesNo, textarea", Value = "" },
                        new { Id = 36, AnamneseChapterId = 5, Label = "Leidet Ihr Kind unter Reiseübelkeit?", MetaInfo = "> 8Jahre, Auto fahren und lesen, Schiffe, Trampolin, Schaukeln, Höhenangst, Karussell, Fahrstuhl, Klettern", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 37, AnamneseChapterId = 5, Label = "Hatte Ihr Kind in den ersten zwei Grundschuljahren Schwierigkeiten, das Lesen zu lernen?", MetaInfo = "Tempo, Betonung, Motivation, spezielle Bücher, Comics", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 38, AnamneseChapterId = 5, Label = "Hatte es Schwierigkeiten beim Schreiben lernen?", MetaInfo = "Sitzhaltung, Stifthaltung, Rechtschreibung, Grammatik, Motorik beim Schreiben, schreiben anstrengend, kann es die Linien halten, drückt es stark auf, sehr kleine Schrift", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 39, AnamneseChapterId = 5, Label = "Falls es zunächst Druckschrift erlernte, hatte es Probleme mit der Schreibschrift?", MetaInfo = "", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 40, AnamneseChapterId = 5, Label = "Hatte Schwierigkeiten, die Uhrzeit ablesen zu lernen (nicht Digitaluhr) bzw. sich insgesamt in der Zeit(Wochentage, Monate etc.) zurecht zu finden ? > 8.LJ", MetaInfo = "räumliche Wahrnehmung, Morgens/ Mittags/ Abends, Gestern/ Morgen, Jahreszeiten, Orientierungssinn, Orientierung im Raum, Geschwindigkeit beim Anziehen, Aufräumen", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 41, AnamneseChapterId = 5, Label = "Hatte es Schwierigkeiten, Fahrradfahren (ohne Stützräder) zu lernen?", MetaInfo = "kann es fahren, seit wann, langsam fahren möglich, wie fährt es", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 42, AnamneseChapterId = 5, Label = "Hatte es Schwierigkeiten, Schwimmen zu lernen?", MetaInfo = "Verhältnis zum Wasser", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 43, AnamneseChapterId = 5, Label = "Konnte es besser unter als über Wasser schwimmen?", MetaInfo = "", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 44, AnamneseChapterId = 5, Label = "Hatte Ihr Kind im Verlauf der ersten 8 Lebensjahre (ausgenommen die ersten 18 Lebensmonate) Krankheiten mit sehr hohem Fieber, Bewusstlosigkeit oder Krämpfen ? ", MetaInfo = "Vollnarkose, Infektanfälligkeit, Antibiotika, Meningitis, Tumore, Frakturen", TextPrefix = "Falls ja, bitte Einzelheiten angeben: ", Type = "radioYesNo, textarea", Value = "" },
                        new { Id = 45, AnamneseChapterId = 5, Label = "War / ist Ihr Kind ein „Hals- Nasen- und Ohren“ Kind, d.h. litt / leidet es an häufigen Infektionen im Hals -, Nasen - und Ohrenbereich ? ", MetaInfo = "Schnupfnase, Mittelohrentzündungen → Hörminderung → Ursache sind dann nicht die Reflexe", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 46, AnamneseChapterId = 5, Label = "Hatte bzw. hat Ihr Kind Schwierigkeiten, einen (kleinen) Ball zu fangen oder andere Auge- / Hand - Koordinationsprobleme ? ", MetaInfo = "Dyspraxie → kleckern beim Essen und Trinken, Fixierungsprobleme, Raum – Zeit – Gefühl gering, Schreckhaft, Verhältnis zu Bällen, Tollpatschig, zu langsam, zu schnell, greift gar nicht, beim hinfallen abgestützt", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 47, AnamneseChapterId = 6, Label = "Hat Ihr Kind Schwierigkeiten still zu sitzen und wird es deswegen ständig vom Lehrer ermahnt ? Bevorzugt es auffällige Sitzpositionen?", MetaInfo = "spinaler Galant (Stuhllehne/Gürtel), W – Sitz, Körperhaltung, Beinhaltung (um den Stuhl geschlungen/ hochgezogenes Bein),Sitzdauer, kippeln, liegend schreibend, Geräuscherzeugung", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 48, AnamneseChapterId = 6, Label = "Macht Ihr Kind zahlreiche Fehler, wenn es aus einem Buch oder von der Tafel abschreibt?", MetaInfo = "", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 49, AnamneseChapterId = 6, Label = "Wenn Ihr Kind in Schule einen Aufsatz schreibt, verdreht es dabei gelegentlich Buchstaben oder lässt einzelne Buchstaben oder Wörter aus(auch evtl.Zahlendreher) ? ", MetaInfo = "lesen von rechts nach links, häufige Dreher > 8LJ", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 50, AnamneseChapterId = 6, Label = "Reagiert Ihr Kind bei plötzlichen, unerwarteten Geräuschen oder Bewegungen auffallend stark?", MetaInfo = "Silvester, Staubsauger, Gewitter, Luftballons, Sportarten, Hobby, bewegt es sich gern, Traumverhalten / Albträume, Schlafhaltung", TextPrefix = "", Type = "radioYesNo", Value = "" },
                        new { Id = 51, AnamneseChapterId = 7, Label = "Zusätzliche Angaben  (z.B. Ernährungsverhalten: Süßigkeiten, Fleisch, Gemüse, Milch; vorangegangene oder andauernde Behandlungen bzw.Therapien(Therapiemüdigkeit), besondere Familiensituationen, Belastungen für das Kind, Kopfschmerzen, Schlafhaltung, Erschöpfung, Hypersensitivität: Geruch / Sonne / Kuscheln / Material / Geschmack / vestibulär):", MetaInfo = "", TextPrefix = "", Type = "textarea", Value = "" }
                    );
                });

            modelBuilder.Entity("rl_contract.Models.Patient", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<DateTime?>("AnamneseDate");

                    b.Property<bool?>("AnamnesePayed");

                    b.Property<string>("Avatar");

                    b.Property<DateTime>("Birthday");

                    b.Property<DateTime?>("DiagnostikDate");

                    b.Property<bool?>("DiagnostikPayed");

                    b.Property<DateTime?>("ElternDate");

                    b.Property<bool?>("ElternPayed");

                    b.Property<string>("Firstname");

                    b.Property<string>("Lastname");

                    b.Property<string>("ProblemHierarchy");

                    b.Property<string>("Tele");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new { Id = 1, Birthday = new DateTime(1988, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), Firstname = "Kleiner", Lastname = "Hase", Tele = "0177123456" },
                        new { Id = 2, Birthday = new DateTime(1988, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), Firstname = "Stefan", Lastname = "Parge", Tele = "0177123457" }
                    );
                });

            modelBuilder.Entity("rl_contract.Models.Review.ProblemHierarchie", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChangedValue");

                    b.Property<string>("InitialValue");

                    b.Property<int?>("ReviewId");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("ProblemHierarchie");
                });

            modelBuilder.Entity("rl_contract.Models.Review.Review", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("ExerciseAccomplishment");

                    b.Property<string>("Exercises");

                    b.Property<string>("Name");

                    b.Property<string>("ObservationsChild");

                    b.Property<string>("ObservationsParents");

                    b.Property<int?>("PatientId");

                    b.Property<bool>("Payed");

                    b.Property<string>("Reasons");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new { Id = 1, Date = new DateTime(2019, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), ExerciseAccomplishment = "Medium ...", Exercises = "Liegestütze und dann Kaffee trinken", Name = "Befundgespräch", ObservationsChild = "Meinung Kind", ObservationsParents = "Meinung Eltern", PatientId = 1, Payed = true, Reasons = "Das war dringend notwendig" },
                        new { Id = 2, Date = new DateTime(2019, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), ExerciseAccomplishment = "Medium ...", Exercises = "Liegestütze und dann Kaffee trinken", Name = "1. Review", ObservationsChild = "Meinung Kind", ObservationsParents = "Meinung Eltern", PatientId = 1, Payed = true, Reasons = "Das war dringend notwendig" },
                        new { Id = 3, Date = new DateTime(2019, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), ExerciseAccomplishment = "Medium ...", Exercises = "Liegestütze und dann Kaffee trinken", Name = "2. Review", ObservationsChild = "Meinung Kind", ObservationsParents = "Meinung Eltern", PatientId = 1, Payed = false, Reasons = "Das war dringend notwendig" },
                        new { Id = 4, Date = new DateTime(2019, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), ExerciseAccomplishment = "Medium ...", Exercises = "Liegestütze und dann Kaffee trinken", Name = "Befundgespräch", ObservationsChild = "Meinung Kind", ObservationsParents = "Meinung Eltern", PatientId = 2, Payed = true, Reasons = "Das war dringend notwendig" },
                        new { Id = 5, Date = new DateTime(2019, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), ExerciseAccomplishment = "Medium ...", Exercises = "Liegestütze und dann Kaffee trinken", Name = "1. Review", ObservationsChild = "Meinung Kind", ObservationsParents = "Meinung Eltern", PatientId = 2, Payed = false, Reasons = "Das war dringend notwendig" },
                        new { Id = 6, Date = new DateTime(2019, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), ExerciseAccomplishment = "Mediums ...", Exercises = "Liegestütze und dann Kaffee trinken", Name = "2. Review", ObservationsChild = "Meinung Kind", ObservationsParents = "Meinung Eltern", PatientId = 2, Payed = false, Reasons = "Das war dringend notwendig" }
                    );
                });

            modelBuilder.Entity("rl_contract.Models.Review.ReviewChapter", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("ReviewId");

                    b.Property<int?>("Score");

                    b.Property<string>("ShortName");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewChapters");
                });

            modelBuilder.Entity("rl_contract.Models.Review.ReviewQuestion", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label");

                    b.Property<int?>("ReviewChapterId");

                    b.Property<string>("Type");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("ReviewChapterId");

                    b.ToTable("ReviewQuestion");
                });

            modelBuilder.Entity("rl_contract.Models.Testung", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name");

                    b.Property<int?>("PatientId");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasFilter("[PatientId] IS NOT NULL");

                    b.ToTable("Testungen");

                    b.HasData(
                        new { Id = 1, Date = new DateTime(2019, 5, 8, 20, 12, 5, 888, DateTimeKind.Local), Name = "Erste Testung", PatientId = 1 }
                    );
                });

            modelBuilder.Entity("rl_contract.Models.TestungChapter", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("Score");

                    b.Property<string>("ShortName");

                    b.Property<int?>("TestungId");

                    b.HasKey("Id");

                    b.HasIndex("TestungId");

                    b.ToTable("TestungChapters");

                    b.HasData(
                        new { Id = 1, Name = "I. TESTS ZUR ÜBERPRÜFUNG DER GROBMOTORISCHEN KOORDINATION UND GLEICHGEWICHT", ShortName = "GROBMOTORISCHE KOORDINATION UND GLEICHGEWICHT", TestungId = 1 },
                        new { Id = 2, Name = "II. TESTS ZUR MOTORISCHEN ENTWICKLUNG", TestungId = 1 },
                        new { Id = 3, Name = "III. TESTS ZUR ÜBERPRÜFUNG VON KLEINHIRNFUNKTIONEN", ShortName = "KLEINHIRNFUNKTIONEN", TestungId = 1 },
                        new { Id = 4, Name = "IV. TESTS ZUR DYSDIADOCHOKINESE", ShortName = "DYSDIADOCHOKINESE", TestungId = 1 },
                        new { Id = 5, Name = "V. LINKS-RECHTS-DISKRIMINIERUNGSPROBLEME", TestungId = 1 },
                        new { Id = 6, Name = "VI. ORIENTIERUNGSPROBLEME", TestungId = 1 },
                        new { Id = 7, Name = "VII. RÄUMLICHE WAHRNEHMUNGSPROBLEME", TestungId = 1 },
                        new { Id = 8, Name = "VIII. TESTS ZU ABERRANTEN REFLEXEN", ShortName = "ABERRANTEN REFLEXEN", TestungId = 1 },
                        new { Id = 9, Name = "IX. TESTS ZUR SEITIGKEITSÜBERPRÜFUNG", TestungId = 1 },
                        new { Id = 10, Name = "X. ÜBERPRÜFUNG DER AUGENMUSKELMOTORIK", ShortName = "AUGENMUSKELMOTORIK", TestungId = 1 },
                        new { Id = 11, Name = "XI. VISUELLE WAHRNEHMUNGSÜBERPRÜFUNG", ShortName = "VISUELLE WAHRNEHMUNGSÜBERPRÜFUNG", TestungId = 1 },
                        new { Id = 12, Name = "ZUSÄTZLICHE BEOBACHTUNGEN UND NOTIZEN", TestungId = 1 },
                        new { Id = 13, Name = "ERGEBNISZUSAMMENFASSUNG", TestungId = 1 }
                    );
                });

            modelBuilder.Entity("rl_contract.Models.TestungQuestion", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label");

                    b.Property<int?>("TestungChapterId");

                    b.Property<string>("Type");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("TestungChapterId");

                    b.ToTable("TestungQuestions");

                    b.HasData(
                        new { Id = 1, Label = "Aufrichten aus Rückenlage in den Stand", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 2, Label = "Aufrichten aus Bauchlage in den Stand", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 3, Label = "Romberg Test (Augen geöffnet)", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 4, Label = "Romberg Test (Augen geschlossen)", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 5, Label = "Mann Test (Augen geöffnet)", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 6, Label = "Mann Test (Augen geschlossen)", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 7, Label = "Einbeinstand", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 8, Label = "Marschieren und Umdrehen", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 9, Label = "Zehenspitzengang (vorwärts) 0 1", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 10, Label = "Zehenspitzengang (rückwärts)", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 11, Label = "Tandem Gang (vorwärts)", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 12, Label = "Tandem Gang (rückwärts)", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 13, Label = "Fog Walk (vorwärts)", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 14, Label = "Fog Walk (rückwärts)", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 15, Label = "Slalom Gang (vorwärts)", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 16, Label = "Slalom Gang (rückwärts)", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 17, Label = "Fersengang (nur vorwärts)", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 18, Label = "Hüpfen auf einem Bein (links oder rechts)", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 19, Label = "Hopserlauf", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 20, Label = "Windmühle", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 21, Label = "Kriechen auf dem Bauch", TestungChapterId = 2, Type = "radio2", Value = "" },
                        new { Id = 22, Label = "Krabbeln auf Händen und Knien", TestungChapterId = 2, Type = "radio3", Value = "" },
                        new { Id = 23, Label = "Ferse auf Schienbein (linke Ferse auf rechtes Schienbein)", TestungChapterId = 3, Type = "radio", Value = "" },
                        new { Id = 24, Label = "Ferse auf Schienbein (rechte Ferse auf linkes Schienbein)", TestungChapterId = 3, Type = "radio", Value = "" },
                        new { Id = 25, Label = "Zeigefinger-Annäherung (Augen offen)", TestungChapterId = 3, Type = "radio", Value = "" },
                        new { Id = 26, Label = "Zeigefinger-Annäherung (Augen geschlossen)", TestungChapterId = 3, Type = "radio", Value = "" },
                        new { Id = 27, Label = "Finger an die Nase (Augen offen)", TestungChapterId = 3, Type = "radio", Value = "" },
                        new { Id = 28, Label = "Finger an die Nase (Augen geschlossen)", TestungChapterId = 3, Type = "radio", Value = "" },
                        new { Id = 29, Label = "Finger (linke Hand)", TestungChapterId = 4, Type = "radio", Value = "" },
                        new { Id = 30, Label = "Finger (rechte Hand)", TestungChapterId = 4, Type = "radio", Value = "" },
                        new { Id = 31, Label = "Hand (links)", TestungChapterId = 4, Type = "radio", Value = "" },
                        new { Id = 32, Label = "Hand (rechts)", TestungChapterId = 4, Type = "radio", Value = "" },
                        new { Id = 33, Label = "Fuß (links)", TestungChapterId = 4, Type = "radio", Value = "" },
                        new { Id = 34, Label = "Fuß (rechts)", TestungChapterId = 4, Type = "radio", Value = "" },
                        new { Id = 35, Label = "Links-Rechts-Diskriminierungsprobleme", TestungChapterId = 5, Type = "radioYesNo", Value = "" },
                        new { Id = 36, Label = "Orientierungsprobleme", TestungChapterId = 6, Type = "radioYesNo", Value = "" },
                        new { Id = 37, Label = "Räumliche Wahrnehmungsprobleme", TestungChapterId = 7, Type = "radioYesNo", Value = "" },
                        new { Id = 38, Label = "Standard Test - linker Arm", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 39, Label = "Standard Test - linkes Bein", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 40, Label = "Standard Test - rechter Arm", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 41, Label = "Standard Test - rechtes Bein", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 42, Label = "Ayres Test Nr. 1 - linker Arm", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 43, Label = "Ayres Test Nr. 1 - rechter Arm", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 44, Label = "Ayres Test Nr. 2 - linker Arm", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 45, Label = "Ayres Test Nr. 2 - rechter Arm", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 46, Label = "Schilder Test - linker Arm", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 47, Label = "Schilder Test - rechter Arm", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 48, Label = "TTNR - von rechts nach links", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 49, Label = "TTNR - von links nach rechts", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 50, Label = "STNR - Füße oder Rumpf", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 51, Label = "STNR - Arme", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 52, Label = "STNR - Krabbeltest", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 53, Label = "Spinaler Galant-Reflex - linke Seite", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 54, Label = "Spinaler Galant-Reflex - rechte Seite", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 55, Label = "TLR - Standard Test", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 56, Label = "TLR - Aufrechttest - Beugung", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 57, Label = "TLR - Aufrechttest – Streckung", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 58, Label = "Moro Reflex / FPR - Standard Test", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 59, Label = "Moro Reflex / FPR - Aufrecht: TT", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 60, Label = "Moro Reflex / FPR - Aufrecht: ZT", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 61, Label = "Moro Reflex / FPR - Aufrecht: FF", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 62, Label = "Augenkopfstellreaktionen - nach links", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 63, Label = "Augenkopfstellreaktionen - nach rechts", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 64, Label = "Augenkopfstellreaktionen - vorwärts", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 65, Label = "Augenkopfstellreaktionen - rückwärts", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 66, Label = "Labyrinthkopfstellreaktionen - nach links", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 67, Label = "Labyrinthkopfstellreaktionen - nach rechts", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 68, Label = "Labyrinthkopfstellreaktionen - rückwärts", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 69, Label = "Labyrinthkopfstellreaktionen - vorwärts", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 70, Label = "Amphibien Reaktion - linke Seite (Rückenlage)", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 71, Label = "Amphibien Reaktion - rechte Seite (Rückenlage)", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 72, Label = "Amphibien Reaktion - linke Seite (Bauchlage)", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 73, Label = "Amphibien Reaktion - rechte Seite (Bauchlage)", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 74, Label = "Segmentäre Rollreaktion- von den Schultern (links)", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 75, Label = "Segmentäre Rollreaktion- von den Schultern (rechts)", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 76, Label = "Segmentäre Rollreaktion- von den Hüften (links)", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 77, Label = "Segmentäre Rollreaktion- von den Hüften (rechts)", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 78, Label = "Babinski Reflex - linker Fuß", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 79, Label = "Babinski Reflex - rechter Fuß", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 80, Label = "Abdominal Reflex (optional)", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 81, Label = "Such-Reflex - links", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 82, Label = "Such-Reflex - rechts", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 83, Label = "Saug-Reflex", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 84, Label = "Erwachsener Saug-Reflex", TestungChapterId = 8, Type = "radio4", Value = "" },
                        new { Id = 85, Label = "Palmar-Reflex - linke Hand", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 86, Label = "Palmar-Reflex - rechte Hand", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 87, Label = "Plantar-Reflex - linker Fuß", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 88, Label = "Plantar-Reflex - rechter Fuß", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 89, Label = "Landau-Reaktion", TestungChapterId = 8, Type = "radio", Value = "" },
                        new { Id = 90, Label = "Fußdominanz - Ball schießen", TestungChapterId = 9, Type = "radioLeftRight", Value = "" },
                        new { Id = 91, Label = "Fußdominanz - Aufstampfen mit einem Fuß", TestungChapterId = 9, Type = "radioLeftRight", Value = "" },
                        new { Id = 92, Label = "Fußdominanz - Auf einen Stuhl steigen", TestungChapterId = 9, Type = "radioLeftRight", Value = "" },
                        new { Id = 93, Label = "Fußdominanz - Auf einem Bein hüpfen", TestungChapterId = 9, Type = "radioLeftRight", Value = "" },
                        new { Id = 94, Label = "Handdominanz - Einen Ball fangen", TestungChapterId = 9, Type = "radioLeftRight", Value = "" },
                        new { Id = 95, Label = "Handdominanz - Klatschen in eine Hand", TestungChapterId = 9, Type = "radioLeftRight", Value = "" },
                        new { Id = 96, Label = "Handdominanz - Schreibhand", TestungChapterId = 9, Type = "radioLeftRight", Value = "" },
                        new { Id = 97, Label = "Handdominanz - Teleskop", TestungChapterId = 9, Type = "radioLeftRight", Value = "" },
                        new { Id = 98, Label = "Augendominanz (Entfernung) - Teleskop", TestungChapterId = 9, Type = "radioLeftRight", Value = "" },
                        new { Id = 99, Label = "Augendominanz (Entfernung) - Ring", TestungChapterId = 9, Type = "radioLeftRight", Value = "" },
                        new { Id = 100, Label = "Augendominanz (Nähe) - Lochkarte", TestungChapterId = 9, Type = "radioLeftRight", Value = "" },
                        new { Id = 101, Label = "Augendominanz (Nähe) - Ring", TestungChapterId = 9, Type = "radioLeftRight", Value = "" },
                        new { Id = 102, Label = "Ohrdominanz - Muschel", TestungChapterId = 9, Type = "radioLeftRight", Value = "" },
                        new { Id = 103, Label = "Ohrdominanz - Lauschen", TestungChapterId = 9, Type = "radioLeftRight", Value = "" },
                        new { Id = 104, Label = "Ohrdominanz - Rufen (Hinweis auf Hemisphärendominanz)", TestungChapterId = 9, Type = "radioLeftRight", Value = "" },
                        new { Id = 105, Label = "Fixierungsschwierigkeiten", TestungChapterId = 10, Type = "radio", Value = "" },
                        new { Id = 106, Label = "Beeinträchtigte Folgebewegungen (tracking- horizontal)", TestungChapterId = 10, Type = "radio", Value = "" },
                        new { Id = 107, Label = "Beeinträchtigte Folgebewegungen (tracking-vertikal)", TestungChapterId = 10, Type = "radio", Value = "" },
                        new { Id = 108, Label = "Verfolgen der Hand mit den Augen (eye-hand-tracking)", TestungChapterId = 10, Type = "radio", Value = "" },
                        new { Id = 109, Label = "Augenzittern (Nystagmus)", TestungChapterId = 10, Type = "radio", Value = "" },
                        new { Id = 110, Label = "Latente Konvergenz - links", TestungChapterId = 10, Type = "radio", Value = "" },
                        new { Id = 111, Label = "Latente Konvergenz - rechts", TestungChapterId = 10, Type = "radio", Value = "" },
                        new { Id = 112, Label = "Latente Divergenz - links", TestungChapterId = 10, Type = "radio", Value = "" },
                        new { Id = 113, Label = "Latente Divergenz - rechts", TestungChapterId = 10, Type = "radio", Value = "" },
                        new { Id = 114, Label = "Konvergenzschwierigkeiten - linkes Auge", TestungChapterId = 10, Type = "radio", Value = "" },
                        new { Id = 115, Label = "Konvergenzschwierigkeiten - rechtes Auge", TestungChapterId = 10, Type = "radio", Value = "" },
                        new { Id = 116, Label = "Schwierigkeit, die Augen unabhängig voneinander zu schließen - linkes Auge", TestungChapterId = 10, Type = "radio", Value = "" },
                        new { Id = 117, Label = "Schwierigkeit, die Augen unabhängig voneinander zu schließen - rechtes Auge", TestungChapterId = 10, Type = "radio", Value = "" },
                        new { Id = 118, Label = "Beeinträchtigung synchroner Augenbewegungen - linkes Auge", TestungChapterId = 10, Type = "radio", Value = "" },
                        new { Id = 119, Label = "Beeinträchtigung synchroner Augenbewegungen - rechtes Auge", TestungChapterId = 10, Type = "radio", Value = "" },
                        new { Id = 120, Label = "Erweiterte periphere Sicht - linkes Auge", TestungChapterId = 10, Type = "radio", Value = "" },
                        new { Id = 121, Label = "Erweiterte periphere Sicht - rechtes Auge", TestungChapterId = 10, Type = "radio", Value = "" },
                        new { Id = 122, Label = "Akkommodationsfähigkeit", TestungChapterId = 10, Type = "radio", Value = "" },
                        new { Id = 123, Label = "Pupillenreaktion auf Licht (optional) - linkes Auge", TestungChapterId = 10, Type = "input", Value = "" },
                        new { Id = 124, Label = "Pupillenreaktion auf Licht (optional) - rechtes Auge", TestungChapterId = 10, Type = "input", Value = "" },
                        new { Id = 125, Label = "Pupillenreaktion auf Licht (optional) - linkes Auge", TestungChapterId = 10, Type = "input", Value = "" },
                        new { Id = 126, Label = "Pupillenreaktion auf Licht (optional) - rechtes Auge", TestungChapterId = 10, Type = "input", Value = "" },
                        new { Id = 127, Label = "Visuelle Unterscheidungsprobleme - Tansley Standard Figuren", TestungChapterId = 11, Type = "radio", Value = "" },
                        new { Id = 128, Label = "Visuelle Unterscheidungsprobleme - Daniels und Diack Figuren", TestungChapterId = 11, Type = "radio", Value = "" },
                        new { Id = 129, Label = "Visuelle Unterscheidungsprobleme - Bender Visual Gestalt Figuren", TestungChapterId = 11, Type = "radio", Value = "" },
                        new { Id = 130, Label = "Visuo-motorische Integrationsschwierigkeit (Auge-Hand-Koordination) - Tansley Standard Figuren", TestungChapterId = 11, Type = "radio", Value = "" },
                        new { Id = 131, Label = "Visuo-motorische Integrationsschwierigkeit (Auge-Hand-Koordination) - Daniels und Diack Figuren", TestungChapterId = 11, Type = "radio", Value = "" },
                        new { Id = 132, Label = "Visuo-motorische Integrationsschwierigkeit (Auge-Hand-Koordination) - Bender Visual Gestalt Figuren", TestungChapterId = 11, Type = "radio", Value = "" },
                        new { Id = 133, Label = "Räumliche Probleme - Tansley Standard Figuren", TestungChapterId = 11, Type = "radio", Value = "" },
                        new { Id = 134, Label = "Räumliche Probleme - Daniels und Diack Figuren", TestungChapterId = 11, Type = "radio", Value = "" },
                        new { Id = 135, Label = "Räumliche Probleme - Bender Visual Gestalt Figuren", TestungChapterId = 11, Type = "radio", Value = "" },
                        new { Id = 136, Label = "Hinweis auf ‘Stimulusgebundenheit’", TestungChapterId = 11, Type = "radio", Value = "" },
                        new { Id = 137, Label = "Abschreiben eines kurzen Textes", TestungChapterId = 11, Type = "input", Value = "" },
                        new { Id = 138, Label = "Mann-Zeichnen-Test Test (Aston Index) - Entwicklungsalter", TestungChapterId = 11, Type = "input", Value = "" },
                        new { Id = 139, Label = "Mann-Zeichnen-Test Test (Aston Index) - Chronologisches Alter", TestungChapterId = 11, Type = "input", Value = "" },
                        new { Id = 140, Label = "Stiftgriff", TestungChapterId = 12, Type = "textarea", Value = "" },
                        new { Id = 141, Label = "Sitzposition", TestungChapterId = 12, Type = "textarea", Value = "" },
                        new { Id = 142, Label = "Schnelle Ermüdbarkeit", TestungChapterId = 12, Type = "textarea", Value = "" },
                        new { Id = 143, Label = "Kind ist ängstlich und besorgt und mit seinen Ergebnissen nicht zufrieden", TestungChapterId = 12, Type = "textarea", Value = "" },
                        new { Id = 144, Label = "Index der Dysfunktion", TestungChapterId = 13, Type = "input", Value = "" },
                        new { Id = 145, Label = "Grobmotorische Koordination und Gleichgewicht", TestungChapterId = 13, Type = "textarea", Value = "" },
                        new { Id = 146, Label = "Kleinhirnfunktionen", TestungChapterId = 13, Type = "textarea", Value = "" },
                        new { Id = 147, Label = "Dysdiadochokinese", TestungChapterId = 13, Type = "textarea", Value = "" },
                        new { Id = 148, Label = "Aberrante Reflexe", TestungChapterId = 13, Type = "textarea", Value = "" },
                        new { Id = 149, Label = "Okulomotorische Funktionen", TestungChapterId = 13, Type = "textarea", Value = "" },
                        new { Id = 150, Label = "Visuelle Wahrnehmungsfunktionen", TestungChapterId = 13, Type = "textarea", Value = "" }
                    );
                });

            modelBuilder.Entity("rl_contract.Models.Anamnese", b =>
                {
                    b.HasOne("rl_contract.Models.Patient")
                        .WithOne("Anamnese")
                        .HasForeignKey("rl_contract.Models.Anamnese", "PatientId");
                });

            modelBuilder.Entity("rl_contract.Models.AnamneseChapter", b =>
                {
                    b.HasOne("rl_contract.Models.Anamnese")
                        .WithMany("Chapters")
                        .HasForeignKey("AnamneseId");
                });

            modelBuilder.Entity("rl_contract.Models.AnamneseQuestion", b =>
                {
                    b.HasOne("rl_contract.Models.AnamneseChapter")
                        .WithMany("Questions")
                        .HasForeignKey("AnamneseChapterId");
                });

            modelBuilder.Entity("rl_contract.Models.Review.ProblemHierarchie", b =>
                {
                    b.HasOne("rl_contract.Models.Review.Review")
                        .WithMany("ProblemHierarchies")
                        .HasForeignKey("ReviewId");
                });

            modelBuilder.Entity("rl_contract.Models.Review.Review", b =>
                {
                    b.HasOne("rl_contract.Models.Patient")
                        .WithMany("Reviews")
                        .HasForeignKey("PatientId");
                });

            modelBuilder.Entity("rl_contract.Models.Review.ReviewChapter", b =>
                {
                    b.HasOne("rl_contract.Models.Review.Review")
                        .WithMany("Chapters")
                        .HasForeignKey("ReviewId");
                });

            modelBuilder.Entity("rl_contract.Models.Review.ReviewQuestion", b =>
                {
                    b.HasOne("rl_contract.Models.Review.ReviewChapter")
                        .WithMany("Questions")
                        .HasForeignKey("ReviewChapterId");
                });

            modelBuilder.Entity("rl_contract.Models.Testung", b =>
                {
                    b.HasOne("rl_contract.Models.Patient")
                        .WithOne("Testung")
                        .HasForeignKey("rl_contract.Models.Testung", "PatientId");
                });

            modelBuilder.Entity("rl_contract.Models.TestungChapter", b =>
                {
                    b.HasOne("rl_contract.Models.Testung")
                        .WithMany("Chapters")
                        .HasForeignKey("TestungId");
                });

            modelBuilder.Entity("rl_contract.Models.TestungQuestion", b =>
                {
                    b.HasOne("rl_contract.Models.TestungChapter")
                        .WithMany("Questions")
                        .HasForeignKey("TestungChapterId");
                });
#pragma warning restore 612, 618
        }
    }
}
